// @ts-nocheck — Example file; types verified via tsx runtime
/**
 * OpenAgentPay Example — Paid Weather API
 *
 * A simple Express weather API that demonstrates the full 402 payment flow:
 *
 *   1. Agent requests weather data without payment → gets 402 with pricing
 *   2. Agent sends request with payment header     → gets weather data + receipt
 *
 * Uses the mock payment adapter — no real money, no wallets, no blockchain.
 * Perfect for development, testing, and understanding the payment flow.
 */

import express from "express";
import { createPaywall } from "@openagentpay/server-express";
import { mock } from "@openagentpay/adapter-mock";
import { getWeather, getForecast } from "./weather-data.js";

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

const PORT = process.env.PORT ? Number.parseInt(process.env.PORT, 10) : 3000;

// ---------------------------------------------------------------------------
// Paywall setup
// ---------------------------------------------------------------------------

const paywall = createPaywall({
  recipient: "0x0000000000000000000000000000000000000000",
  adapters: [mock()],
  subscriptions: {
    plans: [
      {
        id: "hourly-unlimited",
        amount: "0.25",
        currency: "USD",
        period: "hour" as const,
        calls: "unlimited" as const,
        description: "Unlimited calls for one hour",
      },
      {
        id: "daily-1000",
        amount: "2.50",
        currency: "USD",
        period: "day" as const,
        calls: 1000,
        rate_limit: 60,
        description: "1,000 calls per day with 60/min rate limit",
      },
    ],
  },
});

// Log every payment event to the console
paywall.on("payment:received", (receipt) => {
  console.log(
    `  [payment] Received $${receipt.payment.amount} ${receipt.payment.currency} — ${receipt.request.method} ${receipt.request.url}`,
  );
});

paywall.on("payment:failed", (error) => {
  console.log(`  [payment] Failed: ${error.message}`);
});

// ---------------------------------------------------------------------------
// Express app
// ---------------------------------------------------------------------------

const app = express();
app.use(express.json());

// ---------------------------------------------------------------------------
// Routes
// ---------------------------------------------------------------------------

/**
 * GET /api/weather?city=London
 *
 * Static pricing: $0.005 per request.
 * Returns current weather conditions for the specified city.
 */
app.get(
  "/api/weather",
  paywall({
    price: "0.005",
    description: "Current weather conditions",
  }),
  (req, res) => {
    const city = (req.query.city as string) || "London";
    const weather = getWeather(city);

    res.json({
      data: weather,
      _meta: {
        price_charged: "$0.005",
        powered_by: "OpenAgentPay",
      },
    });
  },
);

/**
 * GET /api/forecast?city=London&days=5
 *
 * Dynamic pricing: $0.01 per day of forecast requested.
 * More days = higher cost. Agents can optimize by requesting only what they need.
 */
app.get(
  "/api/forecast",
  paywall((req) => {
    const days = Math.max(1, Math.min(Number.parseInt(req.query.days as string, 10) || 3, 14));
    return {
      price: (0.01 * days).toFixed(3),
      description: `${days}-day weather forecast`,
    };
  }),
  (req, res) => {
    const city = (req.query.city as string) || "London";
    const days = Math.max(1, Math.min(Number.parseInt(req.query.days as string, 10) || 3, 14));
    const forecast = getForecast(city, days);

    res.json({
      data: forecast,
      _meta: {
        days_requested: days,
        price_charged: `$${(0.01 * days).toFixed(3)}`,
        powered_by: "OpenAgentPay",
      },
    });
  },
);

/**
 * GET /api/health
 *
 * Free endpoint — no paywall. Always accessible.
 * Useful for monitoring, load balancers, and agent discovery.
 */
app.get("/api/health", (_req, res) => {
  res.json({
    status: "ok",
    service: "paid-weather-api",
    version: "0.1.0",
    payment_mode: "mock",
    timestamp: new Date().toISOString(),
  });
});

// ---------------------------------------------------------------------------
// Subscription management routes (auto-generated by paywall)
// ---------------------------------------------------------------------------

app.use(paywall.routes());

// ---------------------------------------------------------------------------
// Start server
// ---------------------------------------------------------------------------

app.listen(PORT, () => {
  const banner = `
\u{1F680} OpenAgentPay Example: Paid Weather API
\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}
  GET /api/weather?city=London      $0.005/call
  GET /api/forecast?city=London     $0.01/day
  GET /api/health                   free

  Payment: mock mode (no real money)
  Server:  http://localhost:${PORT}

Try it:
  curl http://localhost:${PORT}/api/weather?city=London
  \u{2192} 402 Payment Required (see pricing)

  curl -H "X-PAYMENT: mock:test123" http://localhost:${PORT}/api/weather?city=London
  \u{2192} 200 OK (weather data + receipt)
\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}\u{2501}`;

  console.log(banner);
});
